from . import hospital_patient_tag
from . import hospital_patient
from . import hospital_appointment_line
from . import hospital_appointment
from . import hospital_doctor
from . import hospital_ward
from . import hospital_nurse
from . import hospital_nurse_assignment
from . import hospital_lab_test_type
from . import hospital_lab_result_image
from . import hospital_lab_test
from . import hospital_prescription_line
from . import hospital_prescription
